const String State_list_api = "https://api.covidfyi.in/v1/states";
const String state_data_api = "https://api.covidfyi.in/v1/state/";

const List StateList = [
  "Andaman and Nicobar",
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chandigarh",
  "Chattisgarh",
  "Dadra and Nagar Haveli",
  "Daman and Diu",
  "Delhi",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jammu and Kashmir",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Ladakh",
  "Lakshadweep",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Puducherry",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal"
];

const List info_types = [
  "Doctors",
  "Fever Clinics",
  "Government Contacts",
  "Helplines",
  "Hospital",
  "Hospitals",
  "Laboratories",
  "Quarantine Facilities",
];
const List info_types1 = [
  "Central Ministry Hospital",
  "Dialysis Center",
  "Doctors",
  "Fever Clinics",
  "Government",
  "Government Contacts",
  "Govt Hospitals",
  "Govt Medical College",
  "Health centre",
  "Helplines",
  "Hospital",
  "Hospitals",
  "Laboratories",
  "Private Hospitals",
  "Private Medical College",
  "Quarantine Facilities",
  "Quarantine Facility",
  "Testing Center",
  "Treatment Hospital"
];
